### ISSUE TITLE
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float

### ISSUE THREAD

**Issue by JCKodel** [leanflutter/flutter_svprogresshud#1]
```
SVProgressHUD.showProgress(100.0 / total * sent, "Sending picture..");
```

(`total` and `sent` are int)

```
E/MethodChannel#flutter_svprogresshud(25835): java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
E/MethodChannel#flutter_svprogresshud(25835): 	at org.blankapp.flutterplugins.flutter_svprogresshud.FlutterSvprogresshudPlugin.onMethodCall(FlutterSvprogresshudPlugin.java:42)
E/MethodChannel#flutter_svprogresshud(25835): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter_svprogresshud(25835): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter_svprogresshud(25835): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#flutter_svprogresshud(25835): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_svprogresshud(25835): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter_svprogresshud(25835): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#flutter_svprogresshud(25835): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/MethodChannel#flutter_svprogresshud(25835): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_svprogresshud(25835): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/MethodChannel#flutter_svprogresshud(25835): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

**Comment by lijy91** [comment]
Please upgrade to 0.0.2

```yaml
dependencies:
  flutter_svprogresshud: ^0.0.2
```
