### ISSUE TITLE
Crash when running on Android 10

### ISSUE THREAD

**Issue by hw20101101** [leanflutter/flutter_svprogresshud#10]
`flutter_svprogresshud: ^0.0.6`

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H15 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.56.2)
```

```
E/flutter (27870): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method dismiss on channel flutter_svprogresshud)
E/flutter (27870): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:157
E/flutter (27870): <asynchronous suspension>
E/flutter (27870): #1      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter (27870): #2      SVProgressHUD.dismiss
package:flutter_svprogresshud/src/svprogresshud.dart:38
E/flutter (27870): #3      _LoginPageState.loginBtnOnPress.<anonymous closure>
package:thrio_example/…/1.1_login_root/login_page.dart:87
E/flutter (27870): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (27870): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (27870): #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (27870): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (27870): #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (27870): #9      Future._complete (dart:async/future_impl.dart:519:7)
E/flutter (27870): #10     new Future.delayed.<anonymous closure> (dart:async/future.dart:323:16)
E/flutter (27870): #11     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (27870): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (27870): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (27870): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (27870): #15     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (27870): #16     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (27870): #17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (27870): #18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (27870): #19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (27870): #20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (27870): #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


```

**Comment by lijy91** [comment]
可以提供一个可复现的项目工程吗？
