### ISSUE TITLE
java.lang.Integer cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by JCKodel** [leanflutter/flutter_svprogresshud#2]
```
E/MethodChannel#flutter_svprogresshud(13277): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
E/MethodChannel#flutter_svprogresshud(13277): 	at org.blankapp.flutterplugins.flutter_svprogresshud.FlutterSvprogresshudPlugin.onMethodCall(FlutterSvprogresshudPlugin.java:42)
E/MethodChannel#flutter_svprogresshud(13277): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter_svprogresshud(13277): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter_svprogresshud(13277): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
E/MethodChannel#flutter_svprogresshud(13277): 	at android.os.MessageQueue.nativePollOnce(Native Method)
```

Code:

```dart
onProgressChanged: (InAppWebViewController controller, int progress) {
  SVProgressHUD.showProgress((progress / 100.0), "Loading...");
},
```

**Comment by lijy91** [comment]
Please upgradle to `0.0.3`
```yaml
dependencies:
  flutter_svprogresshud: ^0.0.3
```
